title: "Dev-Portal"
description: "unify k8s onboarding"
remote_theme: just-the-docs/just-the-docs
favicon_ico: "/resources/images/favicon.ico"

url: https://cloud-native-engineering.github.io/sem05_docs

aux_links:
  Project Planning: https://itcne23.atlassian.net/jira/software/projects/DEV/boards/6

footer_content: "Copyright &copy; 2025 Yves Wetter. Veröffentlicht mit einer <a href=\"https://github.com/Cloud-native-engineering/sem05_docs/tree/main/LICENSE.md\">Creative Commons Attribution-ShareAlike 3.0 Switzerland License</a> Lizenz."

mermaid:
  version: "10.8.0"
